# Generated by Django 4.2.12 on 2024-10-10 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticle',
            new_name='New',
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name_plural': 'News'},
        ),
    ]
