# Generated by Django 4.2.12 on 2024-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_newsarticle_new_alter_new_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='News/images/default.svg', upload_to='News/images/'),
        ),
    ]
