# Generated by Django 4.2.12 on 2024-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='type',
            field=models.ManyToManyField(to='website.category'),
        ),
        migrations.RemoveField(
            model_name='new',
            name='categories',
        ),
        migrations.AddField(
            model_name='new',
            name='categories',
            field=models.CharField(choices=[('BREAKING', 'Breaking News'), ('DEVELOPING', 'Developing Story'), ('URGENT', 'Urgent'), ('LIVE', 'Live Updates'), ('EXCLUSIVE', 'Exclusive')], max_length=20, null=True),
        ),
    ]
