# Generated by Django 4.2.12 on 2024-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_new_type_remove_new_categories_new_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='type',
        ),
        migrations.AddField(
            model_name='new',
            name='newstype',
            field=models.CharField(blank=True, choices=[('BREAKING', 'Breaking News'), ('DEVELOPING', 'Developing Story'), ('URGENT', 'Urgent'), ('LIVE', 'Live Updates'), ('EXCLUSIVE', 'Exclusive')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='new',
            name='categories',
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='news/images/default.svg', upload_to='news/images/'),
        ),
        migrations.AddField(
            model_name='new',
            name='categories',
            field=models.ManyToManyField(to='website.category'),
        ),
    ]
