# Generated by Django 4.2.12 on 2024-10-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='news/images/'),
        ),
    ]
