# Generated by Django 4.2.12 on 2024-10-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='news/images/default.svg', upload_to='news/images/'),
        ),
    ]
