# Generated by Django 4.2.12 on 2024-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='newstype',
            field=models.CharField(blank=True, choices=[('BREAKING', 'Breaking News'), ('DEVELOPING', 'Developing Story'), ('EXCLUSIVE', 'Exclusive')], max_length=20, null=True),
        ),
    ]
