# Generated by Django 4.2.12 on 2024-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_new_newstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='newstype',
            field=models.CharField(blank=True, choices=[('BREAKING', 'خبر فوری'), ('DEVELOPING', 'خبر در حال تکامل'), ('EXCLUSIVE', 'انحصاری')], max_length=20, null=True),
        ),
    ]
