# Generated by Django 4.2.12 on 2024-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_new_newstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='website.tag'),
        ),
    ]
