# Generated by Django 4.2.12 on 2024-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_new_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=models.ManyToManyField(to='website.tag'),
        ),
    ]
